on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  kebab-case-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check filenames for kebab case
        run: |
          cd "$GITHUB_WORKSPACE"

          invalid_files=$(find . -type f -name '*.md' \
            -not -path "./node_modules/*" \
            -not -name "README.md" \
            -not -name "CONTRIBUTING.md" \
            -exec basename {} \; | grep -vE '^[a-z0-9]+(-[a-z0-9]+)*\.md$')

          if [ -n "$invalid_files" ]; then
              echo "The following Markdown filenames are not in kebab case:"
              echo "$invalid_files"
              exit 1 # Fail the job
          else
              echo "All Markdown filenames are in kebab case."
          fi
