name: Check Kebab Case for Changed Markdown Files in PR

on:
  pull_request: # Trigger on PR events
    paths:
      - '**/*.md' # Trigger only when .md files are changed

jobs:
  kebab-case-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         fetch-depth: 2

      - name: Check filenames for kebab case
        run: |
          echo "Checking changed Markdown files for kebab case..."
          changed_files=$(git diff --name-only --diff-filter=AM HEAD^1 HEAD  | grep '\.md$')
          echo "Changed Markdown files:"
          echo "$changed_files"

         
